# Generated by Django 4.1.2 on 2022-11-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(verbose_name='transaction id')),
                ('request_id', models.IntegerField(verbose_name='request id')),
                ('terminal_id', models.IntegerField(verbose_name='terminal id')),
                ('partner_object_id', models.IntegerField(verbose_name='partner object id')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount total')),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount original')),
                ('commission_ps', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission PS')),
                ('commission_client', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission client')),
                ('commission_provider', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission provider')),
                ('date_input', models.DateTimeField(verbose_name='date input')),
                ('date_post', models.DateTimeField(verbose_name='date post')),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('DEC', 'declined')], default='ACC', max_length=20, verbose_name='status')),
                ('payment_type', models.CharField(choices=[('CASH', 'cash'), ('CARD', 'card')], default='CASH', max_length=20, verbose_name='payment type')),
                ('payment_number', models.CharField(max_length=20, verbose_name='payment number')),
                ('service_id', models.IntegerField(verbose_name='service id')),
                ('service', models.CharField(choices=[('REP', 'replenishment_of_the_card')], default='REP', max_length=20, verbose_name='service')),
                ('payee_id', models.IntegerField(verbose_name='payee id')),
                ('payee_name', models.CharField(choices=[('PUMB', 'pumb'), ('PRIVAT', 'privat'), ('OSCHAD', 'oschad')], default='PRIVAT', max_length=20, verbose_name='payee name')),
                ('payee_bank_mfo', models.IntegerField(verbose_name='payee bank mfo')),
                ('payee_bank_account', models.CharField(max_length=20, verbose_name='payee bank account')),
                ('payment_narrative', models.CharField(choices=[('MT', 'money_transfer')], default='MT', max_length=200, verbose_name='payment narrative')),
            ],
            options={
                'verbose_name': 'file info',
                'verbose_name_plural': 'file info`s',
                'db_table': 'app_file_loading',
            },
        ),
        migrations.CreateModel(
            name='FileUploading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='files/%Y/%m/%d', verbose_name='csv file')),
            ],
            options={
                'verbose_name_plural': 'file uploading',
                'db_table': 'file_uploading',
            },
        ),
    ]
